export * from './Footer/Footer'
export * from './MovieList/MovieList'
export * from './Header/Header'
export * from './Home/Home'
export * from './MovieDetail/MovieDetail'
export * from './PageNotFound/PageNotFound'
export * from './Layout/Layout'